services:
    jetbrains-gateway-ssh:
        image: jetbrains-gateway-ssh
        build: src
        environment:
            SSH_USERNAME: "${SSH_USERNAME:-jetbrains}"
            SSH_PASSWORD: "${SSH_PASSWORD:-jetbrains}"
            SSH_UID: "${SSH_UID:-1001}"
            SSH_GID: "${SSH_GID:-1001}"
            FIX_HOME_OWNERSHIP: "${FIX_HOME_OWNERSHIP:-false}"
        volumes:
            - "./home:/opt/home"
            # - "./setup.sh:/opt/setup.sh"
        ports:
            - "${SSH_PORT:-22}:22"
